version: "3.9"
services:
  archan-bot:
    build: .
    container_name: archan-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start